export const ProjectAction = {
    PROJECT_LIST_R: 'PROJECT_LIST_R',
    PROJECT_LIST_S: 'PROJECT_LIST_S',
    PROJECT_FORM_R: 'PROJECT_FORM_R',
    PROJECT_FORM_S: 'PROJECT_FORM_S',
    PROJECT_CREATE_R: 'PROJECT_CREATE_R',
    PROJECT_CREATE_S: 'PROJECT_CREATE_S',
    PROJECT_STORE: 'PROJECT_STORE',
    PROJECT_UPDATE: 'PROJECT_UPDATE',
    PROJECT_SELECT_DELETE_R: 'PROJECT_SELECT_DELETE_R',
    PROJECT_DELETE_R: 'PROJECT_DELETE_R',
    PROJECT_DELETE_FILE_R: 'PROJECT_DELETE_FILE_R',
    PROJECT_LIST_FILES_S: 'PROJECT_LIST_FILES_S',
    PROJECT_SPRINT_R: 'PROJECT_SPRINT_R',
    PROJECT_SPRINT_S: 'PROJECT_SPRINT_S',
    PROJECT_SPRINT_DELETE_R: 'PROJECT_SPRINT_DELETE_R',
};
  