export const MenusAction = {
    MENUS_LIST_R: 'MENUS_LIST_R',
    MENUS_LIST_S: 'MENUS_LIST_S',
    MENUS_CRUMBS_LIST_S: 'MENUS_CRUMBS_LIST_S',
    MENUS_HEADER_S: 'MENUS_HEADER_S',
    MENUS_RESET_S: 'MENUS_RESET_S',
}