export const ReportAction = {
    BYPROJECT_LIST_R: 'BYPROJECT_LIST_R',
    BYPROJECT_LIST_S: 'BYPROJECT_LIST_S',
    BYSTAFF_LIST_R: 'BYSTAFF_LIST_R',
    BYSTAFF_LIST_S: 'BYSTAFF_LIST_S',
    OVERALL_LIST_R: 'OVERALL_LIST_R',
    OVERALL_LIST_S: 'OVERALL_LIST_S',
};