export const BoardAction = {
    BOARD_LIST_R: 'BOARD_LIST_R',
    BOARD_LIST_S: 'BOARD_LIST_S',
    BOARD_NAME_R: 'BOARD_NAME_R',
    BOARD_NAME_S: 'BOARD_NAME_S',
    BOARD_SPRINT_R: 'BOARD_SPRINT_R',
    BOARD_SPRINT_S: 'BOARD_SPRINT_S'
};