export const TaskAction = {
    TASK_LIST_R: 'TASK_LIST_R',
    TASK_LIST_S: 'TASK_LIST_S',
    TASK_FORM_R: 'TASK_FORM_R',
    TASK_FORM_S: 'TASK_FORM_S',
    TASK_STORE: 'TASK_STORE',
    TASK_UPDATE: 'TASK_UPDATE',
    TASK_SELECT_DELETE_R: 'TASK_SELECT_DELETE_R',
    TASK_DELETES_R: 'TASK_DELETES_R',
    TASK_DELETE_R: 'TASK_DELETE_R',
    TASK_DELETE_FILE_R: 'TASK_DELETE_FILE_R',
    TASK_LIST_FILES_S: 'TASK_LIST_FILES_S',
};
