export const RoadmapAction = {
    ROADMAP_LIST_R: 'ROADMAP_LIST_R',
    ROADMAP_LIST_S: 'ROADMAP_LIST_S',
    ROADMAP_FORM_R: 'ROADMAP_FORM_R',
    ROADMAP_FORM_S: 'ROADMAP_FORM_S',
    ROADMAP_STORE: 'ROADMAP_STORE',
    ROADMAP_UPDATE: 'ROADMAP_UPDATE',
    ROADMAP_SELECT_DELETE_R: 'ROADMAP_SELECT_DELETE_R',
    ROADMAP_DELETES_R: 'ROADMAP_DELETES_R',
    ROADMAP_DELETE_R: 'ROADMAP_DELETE_R',
    ROADMAP_DELETE_FILE_R: 'ROADMAP_DELETE_FILE_R',
    ROADMAP_LIST_FILES_S: 'ROADMAP_LIST_FILES_S'
};