export const CentralAction = {
    CENTRAL_RESOURCE_R: 'CENTRAL_RESOURCE_R',
    CENTRAL_RESOURCE_S: 'CENTRAL_RESOURCE_S',
    CENTRAL_PROJECT_R: 'CENTRAL_PROJECT_R',
    CENTRAL_PROJECT_S: 'CENTRAL_PROJECT_S',
    CENTRAL_TASK_R: 'CENTRAL_TASK_R',
    CENTRAL_TASK_S: 'CENTRAL_TASK_S',
    CENTRAL_SPRINT_R: 'CENTRAL_SPRINT_R',
    CENTRAL_SPRINT_S: 'CENTRAL_SPRINT_S',
    CENTRAL_DELETE_FILE_R: 'CENTRAL_DELETE_FILE_R',
    CENTRAL_RESOURCE_BYSTAFF_R: 'CENTRAL_RESOURCE_BYSTAFF_R',
    CENTRAL_RESOURCE_BYSTAFF_S: 'CENTRAL_RESOURCE_BYSTAFF_S',
};